#!/usr/bin/env node
// Copies third-party runtime assets (fonts, GSAP) from tools/node_modules into
// assets/. Re-run after upgrading the npm packages. The site never loads
// anything from node_modules or a CDN at runtime.
//
//   node tools/vendor.mjs
//
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from 'esbuild';

const TOOLS = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(TOOLS, '..');
const NM = path.join(TOOLS, 'node_modules');

const mkdir = (p) => fs.mkdirSync(p, { recursive: true });

// ---------------------------------------------------------------- fonts
// Variable woff2, latin + latin-ext subsets. Fraunces "full" keeps every axis
// (opsz, wght, SOFT, WONK); Source Serif 4 "standard" keeps opsz + wght;
// Inter "wght" is enough for UI sizes.
const FONTS = [
  ['@fontsource-variable/fraunces', 'fraunces', 'full', ['normal', 'italic']],
  ['@fontsource-variable/source-serif-4', 'source-serif-4', 'standard', ['normal', 'italic']],
  ['@fontsource-variable/inter', 'inter', 'wght', ['normal', 'italic']],
];
const fontDir = path.join(ROOT, 'assets/fonts');
mkdir(fontDir);
for (const [pkg, slug, axes, styles] of FONTS) {
  for (const subset of ['latin', 'latin-ext']) {
    for (const style of styles) {
      const src = path.join(NM, pkg, 'files', `${slug}-${subset}-${axes}-${style}.woff2`);
      const dest = path.join(fontDir, `${slug}-${subset}-${style}.woff2`);
      fs.copyFileSync(src, dest);
    }
  }
  fs.copyFileSync(path.join(NM, pkg, 'LICENSE'), path.join(fontDir, `${slug}-OFL.txt`));
}
console.log('fonts  → assets/fonts/');
console.log('       ! also regenerate assets/fonts/fraunces-amp-italic.woff2 (italic "&" subset, see tools/README.md → fonts)');

// ---------------------------------------------------------------- GSAP
// Copy the ES-module build, minified file-by-file (imports stay relative, so
// the browser resolves them natively). Only what figures are likely to need.
const GSAP_SRC = path.join(NM, 'gsap');
const GSAP_DEST = path.join(ROOT, 'assets/vendor/gsap');
const ENTRY_FILES = [
  ['index.js', 'gsap.js'], // core + CSSPlugin (GSAP's own entry)
  'gsap-core.js',
  'CSSPlugin.js',
  'MotionPathPlugin.js',
  'MorphSVGPlugin.js',
  'DrawSVGPlugin.js',
  'CustomEase.js',
  'EasePack.js',
  'Flip.js',
  'Draggable.js',
  'InertiaPlugin.js',
  'TextPlugin.js',
];
mkdir(path.join(GSAP_DEST, 'utils'));
const done = new Set();
async function copyModule(rel, destRel = rel) {
  if (done.has(destRel)) return;
  done.add(destRel);
  const code = fs.readFileSync(path.join(GSAP_SRC, rel), 'utf8');
  const out = await transform(code, { minify: true, format: 'esm', target: 'es2019', legalComments: 'inline' });
  fs.writeFileSync(path.join(GSAP_DEST, destRel), out.code);
  // follow relative imports
  for (const m of code.matchAll(/from\s+"(\.\/[^"]+)"/g)) {
    const dep = path.posix.normalize(path.posix.join(path.posix.dirname(rel), m[1]));
    await copyModule(dep);
  }
}
for (const f of ENTRY_FILES) {
  const [src, dest] = Array.isArray(f) ? f : [f, f];
  await copyModule(src, dest);
}

// Site entry: one import gives a gsap instance with the common plugins
// registered. Figure modules normally use ctx.gsap instead of importing.
const pkgVersion = JSON.parse(fs.readFileSync(path.join(GSAP_SRC, 'package.json'), 'utf8')).version;
fs.writeFileSync(
  path.join(GSAP_DEST, 'index.js'),
  `// Self & Other — GSAP ${pkgVersion} entry (generated by tools/vendor.mjs; do not edit).
// import { gsap, MotionPathPlugin, MorphSVGPlugin, DrawSVGPlugin, CustomEase } from '<relative>/assets/vendor/gsap/index.js';
// Draggable, Flip, InertiaPlugin, TextPlugin, EasePack are vendored too: import
// them from their own files and call gsap.registerPlugin(...) yourself.
import { gsap } from './gsap.js';
import { MotionPathPlugin } from './MotionPathPlugin.js';
import { MorphSVGPlugin } from './MorphSVGPlugin.js';
import { DrawSVGPlugin } from './DrawSVGPlugin.js';
import { CustomEase } from './CustomEase.js';

gsap.registerPlugin(MotionPathPlugin, MorphSVGPlugin, DrawSVGPlugin, CustomEase);

// House eases (see docs/DESIGN.md → Motion). Physical, calm, never bouncy.
CustomEase.create('so.inOut', 'M0,0 C0.45,0 0.2,1 1,1');
CustomEase.create('so.out', 'M0,0 C0.15,0.6 0.25,1 1,1');
CustomEase.create('so.in', 'M0,0 C0.55,0 0.85,0.4 1,1');

export { gsap, MotionPathPlugin, MorphSVGPlugin, DrawSVGPlugin, CustomEase };
export default gsap;
`
);
fs.writeFileSync(
  path.join(GSAP_DEST, 'LICENSE.txt'),
  `GSAP ${pkgVersion} — Copyright (c) 2008-2026, GreenSock. All rights reserved.\n` +
    `Free for all uses under GreenSock's standard "no charge" license: https://gsap.com/standard-license\n` +
    `Vendored (ES-module build, minified per file) by tools/vendor.mjs from the npm package "gsap".\n`
);
console.log(`gsap ${pkgVersion} → assets/vendor/gsap/ (${[...done].length} modules)`);
